import { PropertyList } from './types';
import Sample from '../../../assets/images/sample.png';
import LandImg2 from '../../../assets/images/land-img-2.png';
import LandImg3 from '../../../assets/images/land-img-3.png';
import Imagereader1 from '../../../assets/images/imagereader 1.png';
import ViewHome1 from '../../../assets/images/mobile/view-home1.svg';
import ViewHome2 from '../../../assets/images/mobile/view-home2.svg';

export const mockProperties: PropertyList = [
  {
    id: '1',
    title: 'Chennai - Modern Ocean View Villa',
    location: 'Chennai, Tamil Nadu, India',
    price: 6000000,
    bedrooms: 5,
    bathrooms: 7,
    sqft: 14850,
    image: Sample,
    images: [Sample, LandImg2, LandImg3],
    description: 'Modern villa with ocean views, 5 bedrooms, 7 bathrooms, and luxury amenities in Chennai.',
    isSaved: true,
    lat: 13.0827,
    lng: 80.2707,
  },
  {
    id: '2',
    title: 'Coimbatore - Riverside Villa with Pool',
    location: 'Coimbatore, Tamil Nadu, India',
    price: 3250000,
    bedrooms: 6,
    bathrooms: 8,
    sqft: 7850,
    image: LandImg2,
    images: [LandImg2, Imagereader1, Sample],
    description: 'Riverside villa with a huge pool, 6 bedrooms, 8 bathrooms, and scenic views in Coimbatore.',
    isSaved: false,
    lat: 11.0168,
    lng: 76.9558,
  },
  {
    id: '3',
    title: 'Madurai - 4BR Villa with Temple Views',
    location: 'Madurai, Tamil Nadu, India',
    price: 3100000,
    bedrooms: 4,
    bathrooms: 6,
    sqft: 9200,
    image: LandImg3,
    images: [LandImg3, Sample, ViewHome1],
    description: '4 bedroom villa with breathtaking temple views, modern design, and spacious living areas in Madurai.',
    isSaved: false,
    lat: 9.9252,
    lng: 78.1198,
  },
  {
    id: '4',
    title: 'Tiruchirappalli - Gorgeous 5BR Villa Near River',
    location: 'Tiruchirappalli, Tamil Nadu, India',
    price: 5000000,
    bedrooms: 5,
    bathrooms: 7,
    sqft: 12000,
    image: Imagereader1,
    images: [Imagereader1, LandImg2, ViewHome2],
    description: 'Gorgeous 5 bedroom villa near the river, with luxury finishes and a private pool in Tiruchirappalli.',
    isSaved: true,
    lat: 10.7905,
    lng: 78.7047,
  },
  {
    id: '5',
    title: 'Salem - Modern Family Home with Private Garden',
    location: 'Salem, Tamil Nadu, India',
    price: 1200000,
    bedrooms: 3,
    bathrooms: 4,
    sqft: 3500,
    image: ViewHome1,
    images: [ViewHome1, ViewHome2, Sample],
    description: 'A modern family home with a private garden and spacious living areas in Salem.',
    isSaved: false,
    lat: 11.6643,
    lng: 78.1460,
  },
  {
    id: '6',
    title: 'Erode - Luxury Penthouse with City Views',
    location: 'Erode, Tamil Nadu, India',
    price: 2200000,
    bedrooms: 4,
    bathrooms: 5,
    sqft: 5000,
    image: ViewHome2,
    images: [ViewHome2, LandImg3, Imagereader1],
    description: 'Luxury penthouse with panoramic city views and top amenities in Erode.',
    isSaved: true,
    lat: 11.3410,
    lng: 77.7172,
  },
  {
    id: '7',
    title: 'Chennai - Luxury Beachside Villa',
    location: 'Chennai, Tamil Nadu, India',
    price: 1500000,
    bedrooms: 4,
    bathrooms: 5,
    sqft: 6000,
    image: Sample,
    images: [Sample, LandImg2, LandImg3],
    description: 'Luxury beachside villa in Chennai with modern amenities and sea views.',
    isSaved: false,
    lat: 13.0827,
    lng: 80.2707,
  },
  // Add more mock properties as needed
]; 